exclude           = [  ]
force-exclude     = true
indent-width      = 4
line-length       = 120
respect-gitignore = true
target-version    = "py313"
unsafe-fixes      = true

[format]
  docstring-code-format      = true
  docstring-code-line-length = "dynamic"
  indent-style               = "space"
  line-ending                = "lf"
  quote-style                = "single"
  skip-magic-trailing-comma  = false

[lint]
  fixable   = [ "ALL" ]
  select    = [ "ALL" ]
  unfixable = [  ]

  ignore = [
    "ANN401", # any-type
    "COM",    # flake8-commas
    "D1",     # undocumented-{module,class,method,...}
    "INP001", # implicit-namespace-package
    "PYI021", # docstring-in-stub
    "SIM102", # collapsible-if
    "SLF001", # private-member-access
    "T201",   # print
  ]

  [lint.per-file-ignores]
    "*test*" = [ "ANN", "D", "N", "Q", "S" ]

  [lint.isort]
    known-first-party = [ "typed_sentinels" ]

  [lint.flake8-unused-arguments]
    ignore-variadic-names = true

  [lint.flake8-annotations]
    allow-star-arg-any = true

  [lint.flake8-quotes]
    inline-quotes = "single"

  [lint.pydocstyle]
    convention = "numpy"

  [lint.pylint]
    allow-magic-value-types = [ "float", "int", "str" ]
    max-args                = 20
    max-bool-expr           = 10
    max-branches            = 20
    max-locals              = 15
    max-nested-blocks       = 10
    max-positional-args     = 20
    max-returns             = 10
    max-statements          = 75

  [lint.flake8-bugbear]
    extend-immutable-calls = [  ]
