force-exclude = true
indent-width = 4
line-length = 120
respect-gitignore = true
target-version = "py313"
# unsafe-fixes      = true

exclude = []

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
quote-style = "single"
skip-magic-trailing-comma = false

[lint]
fixable = ["ALL"]
select = ["ALL"]
unfixable = []

ignore = [
  "ANN401",  # any-type
  "BLE001",  # blind-except
  "C901",    # complex-structure
  "COM",     # flake8-commas
  "D1",      # pydocstyle
  "D2",      # pydocstyle
  "D414",    # empty-docstring-section
  "D417",    # undocumented-param
  "ERA001",  # commented-out-code
  "EXE003",  # shebang-missing-python
  "F401",    # unused-import
  "FIX002",  # line-contains-todo
  "INP001",  # implicit-namespace-package
  "N817",    # camelcase-imported-as-acronym
  "N818",    # error-suffix-on-exception-name
  "PLC0414", # useless-import-alias
  "PLC0415", # import-outside-top-level
  "PLR2004", # magic-value-comparison
  "PLW0603", # global-statement
  "PTH",     # flake8-use-pathlib
  "PYI021",  # docstring-in-stub
  "S108",    # hardcoded-temp-file
  "S112",    # try-except-continue
  "S311",    # suspicious-non-cryptographic-random-usage
  "S6",      # flake8-bandit
  "S701",    # jinja2-autoescape-false
  "SIM102",  # collapsible-if
  "SLF001",  # private-member-access
  "T201",    # print
  "T203",    # p-print
  "TD002",   # missing-todo-author
  "TD003",   # missing-todo-link
]

[lint.isort]
known-first-party = []

[lint.per-file-ignores]
"*codemod*" = [
  "ARG002", # unused-method-argument
  "N802",   # invalid-function-name
]

"*.pyi" = [
  "D404", # docstring-starts-with-this
]

"*compat*" = [
  "UP", # pyupgrade
]

"*test*" = [
  "ANN001", # missing-type-function-argument
  "ARG002", # unused-method-argument
  "D",      # pydocstyle
  "Q000",   # bad-quotes-inline-string
  "S101",   # assert
]

"__init__.py" = [
  "D103", # undocumented-public-function
  "D104", # undocumented-public-package
  "F401", # unused-import
  "F403", # undefined-local-with-import-star
  "F405", # undefined-local-with-import-star-usage
]

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "numpy"

[lint.pylint]
allow-magic-value-types = ["float", "int", "str"]
max-args = 20
max-bool-expr = 10
max-branches = 20
max-locals = 15
max-nested-blocks = 10
max-positional-args = 20
max-returns = 10
max-statements = 75

[lint.flake8-bugbear]
extend-immutable-calls = []
